name: Auto Merge to Main

on:
  pull_request_target:
    types: [closed]
    branches:
      - main


jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Automatic Merge
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"
          git push origin main

      - name: Notify Merge Success
        run: echo "Merge completed successfully!"
