name: Deploy and Auto Merge on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock coverage
      - name: Run tests
        run: |
          pytest
      - name: Check code coverage
        run: |
          coverage run -m pytest
          coverage report
      - name: Simulate Deployment
        if: success()
        run: |
          echo "Simulating deployment to production..."
          echo "Deployment successful!"
      - name: Auto Merge
        if: success()
        uses: pascalgn/automerge-action@v0.14.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          mergeMethod: merge
