name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Deploy
      if: success()
      run: |
        echo "Deploying application..."
        # Simular um deploy, e.g., copiar arquivos, executar scripts de deploy, etc.
        # Supondo que o deploy seria para um diretório local no servidor de CI
        mkdir -p /var/www/myapp
        cp -r * /var/www/myapp/
        echo "Deploy successful!"
