name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests
      run: |
        pytest

    - name: Check code coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Deploy to Production
      if: success()
      run: |
        echo "Deploying to production..."
        # Aqui você colocaria seu script de deploy, como rsync, scp, scripts SSH, etc.
        echo "Deployment successful!"
