name: Run Tests on Commit

on:
  push:
    branches:
      - development
jobs:
  check_previous_workflow_success:
    runs-on: ubuntu-latest
    steps:
      - name: Check last workflow run status
        id: check_run
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const payload = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'development',
              workflow_id: 'test.yml'
            });
            const run = payload.data.workflow_runs[0];
            if (run.conclusion == 'success') {
              return 'success';
            } else {
              return 'failure';
            }
      - name: Trigger if previous was successful
        if: steps.check_run.outputs.result == 'success'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update from Development
          title: 'Merge Development Changes into Main'
          body: 'This is an automatically generated pull request to merge changes from the development branch into the main branch.'
          base: main
          branch: 'merge-development-to-main-${{ github.run_number }}'
          delete-branch: true
          draft: false
